### ISSUE TITLE
Thank you for writing this book. I have a question.

### ISSUE THREAD

**Issue by blitzerr** [d0iasm/book.rvemu#1]
I am looking to follow along with your book. Would you mind explaining to me why is it necessary to install [the tool chain](https://github.com/d0iasm/book.rvemu/blob/master/setup-and-implement-two-instructions.md#build-risc-v-toolchain) ? The program we are writing is able to execute a riscv compliant asm file, right ?

**Comment by d0iasm** [comment]
Thank you for your question!

The reason to install the toolchain is not to use the compressed instructions (RV64C) when we compile C code and xv6 code in the future. The default toolchain for RISC-V in my environment uses the compressed instructions that we'll not implement. The default setting for the toolchain might be different depending on the environment and I just make sure that we have the same setting for the toolchain.
